version: '3'

services:
  apigateway:
    container_name: apigateway
    image: apigateway:v1
    build:
      context: apigateway
      dockerfile: Dockerfile
    environment:
      SERVICE_A: "http://service_a:8081"
      SERVICE_B: "http://service_b:8082"
      CLIENT: "https://client:8087"
    depends_on:
      - service_a
      - service_b
    deploy:
      replicas: 1

  service_a:
    container_name: service_a
    image: service_a:v1
    build:
      context: services/service-a
      dockerfile: Dockerfile
    environment:
      SERVICE_B: "http://service_b:8082"
    depends_on:
      - service_b
    deploy:
      replicas: 1

  service_b:
    container_name: service_b
    image: service_b:v1
    build:
      context: services/service-b
      dockerfile: Dockerfile
    environment:
      DB_CONN: "mysql+mysqlconnector://root:pass123@database:3306/Library" # this should be a secret
    depends_on:
      - database
    deploy:
      replicas: 1

  client:
    container_name: client
    image: client:v1
    build:
      context: client
      dockerfile: Dockerfile
    deploy: 
      replicas: 1

  #When creating a real app remove this and create a db
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_DATABASE: Library
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - 3306:3306
    volumes:
      - "./database/init.sql:/docker-entrypoint-initdb.d/init.sql"

  proxy:
    image: nginx:latest
    depends_on:
      - client
      - apigateway
      - service_a
      - service_b
    ports:
      - 443:443
    volumes:
      - ./cert:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf